-- Rezeptfinder v1.33: Cloud-Backups / Versionierung + kein Login

-- Falls du vorher Login/RLS aktiviert hast, erlaubt dieser Block deiner privaten App wieder den Zugriff mit dem anon key.
alter table public.rezepte enable row level security;

drop policy if exists "Eigene Rezepte lesen" on public.rezepte;
drop policy if exists "Eigene Rezepte erstellen" on public.rezepte;
drop policy if exists "Eigene Rezepte aktualisieren" on public.rezepte;
drop policy if exists "Eigene Rezepte löschen" on public.rezepte;

drop policy if exists "Rezepte lesen erlauben" on public.rezepte;
drop policy if exists "Rezepte erstellen erlauben" on public.rezepte;
drop policy if exists "Rezepte aktualisieren erlauben" on public.rezepte;
drop policy if exists "Rezepte löschen erlauben" on public.rezepte;

create policy "Rezepte lesen erlauben"
on public.rezepte
for select
to anon
using (true);

create policy "Rezepte erstellen erlauben"
on public.rezepte
for insert
to anon
with check (true);

create policy "Rezepte aktualisieren erlauben"
on public.rezepte
for update
to anon
using (true)
with check (true);

create policy "Rezepte löschen erlauben"
on public.rezepte
for delete
to anon
using (true);

create table if not exists public.rezept_backups (
  id bigint generated by default as identity primary key,
  erstellt_am timestamp with time zone default now(),
  grund text,
  anzahl integer,
  daten jsonb not null
);

alter table public.rezept_backups enable row level security;

drop policy if exists "Backups lesen erlauben" on public.rezept_backups;
drop policy if exists "Backups erstellen erlauben" on public.rezept_backups;
drop policy if exists "Backups löschen erlauben" on public.rezept_backups;

create policy "Backups lesen erlauben"
on public.rezept_backups
for select
to anon
using (true);

create policy "Backups erstellen erlauben"
on public.rezept_backups
for insert
to anon
with check (true);

create policy "Backups löschen erlauben"
on public.rezept_backups
for delete
to anon
using (true);
