-- Rezeptfinder v2.54: Supabase Setup / Cloud-Backups / Versionierung ohne Login
-- Hinweis: Diese Variante erlaubt dem anon key Lesen/Schreiben/Löschen.
-- Für eine öffentlich verteilte App sollte später Auth + nutzerbezogene RLS verwendet werden.

create table if not exists public.rezepte (
  id text primary key,
  name text,
  daten jsonb,
  aktualisiert_am timestamp with time zone default now()
);

alter table public.rezepte
  add column if not exists name text,
  add column if not exists daten jsonb,
  add column if not exists aktualisiert_am timestamp with time zone default now();

alter table public.rezepte enable row level security;

drop policy if exists "Eigene Rezepte lesen" on public.rezepte;
drop policy if exists "Eigene Rezepte erstellen" on public.rezepte;
drop policy if exists "Eigene Rezepte aktualisieren" on public.rezepte;
drop policy if exists "Eigene Rezepte löschen" on public.rezepte;
drop policy if exists "Rezepte lesen erlauben" on public.rezepte;
drop policy if exists "Rezepte erstellen erlauben" on public.rezepte;
drop policy if exists "Rezepte aktualisieren erlauben" on public.rezepte;
drop policy if exists "Rezepte löschen erlauben" on public.rezepte;

create policy "Rezepte lesen erlauben"
on public.rezepte
for select
to anon
using (true);

create policy "Rezepte erstellen erlauben"
on public.rezepte
for insert
to anon
with check (true);

create policy "Rezepte aktualisieren erlauben"
on public.rezepte
for update
to anon
using (true)
with check (true);

create policy "Rezepte löschen erlauben"
on public.rezepte
for delete
to anon
using (true);

create table if not exists public.rezept_backups (
  id bigint generated by default as identity primary key,
  erstellt_am timestamp with time zone default now(),
  grund text,
  anzahl integer,
  daten jsonb not null
);

alter table public.rezept_backups enable row level security;

drop policy if exists "Backups lesen erlauben" on public.rezept_backups;
drop policy if exists "Backups erstellen erlauben" on public.rezept_backups;
drop policy if exists "Backups löschen erlauben" on public.rezept_backups;

create policy "Backups lesen erlauben"
on public.rezept_backups
for select
to anon
using (true);

create policy "Backups erstellen erlauben"
on public.rezept_backups
for insert
to anon
with check (true);

create policy "Backups löschen erlauben"
on public.rezept_backups
for delete
to anon
using (true);

-- Rezeptfinder v2.54: zusätzliche Stabilität für Cloud-Suche und Backups
create index if not exists rezepte_name_idx on public.rezepte using btree (name);
create index if not exists rezepte_aktualisiert_am_idx on public.rezepte using btree (aktualisiert_am desc);
create index if not exists rezept_backups_erstellt_am_idx on public.rezept_backups using btree (erstellt_am desc);

alter table public.rezept_backups
  add column if not exists app_version text default '2.54';
